apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-proxy-pg-pvc
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-proxy-pg
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-proxy-pg
  template:
    metadata:
      labels:
        app: zabbix-proxy-pg
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: zabbix
            - name: POSTGRES_PASSWORD
              value: zabbix_pass
            - name: POSTGRES_DB
              value: zabbix_proxy
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zabbix-proxy-pg-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-proxy-pg
  namespace: zabbix
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: zabbix-proxy-pg
