apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-postgres-pvc
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-postgres
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-postgres
  template:
    metadata:
      labels:
        app: zabbix-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: zabbix
            - name: POSTGRES_PASSWORD
              value: zabbix_pass
            - name: POSTGRES_DB
              value: zabbix
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: zabbix-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgres
  namespace: zabbix
spec:
  selector:
    app: zabbix-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
