apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-config
  namespace: zabbix
data:
  zabbix_agentd.conf: |
    Server=zabbix-server
    ServerActive=zabbix-server
    Hostname=k8s-agent
    LogType=console
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  namespace: zabbix
spec:
  selector:
    matchLabels:
      app: zabbix-agent
  template:
    metadata:
      labels:
        app: zabbix-agent
    spec:
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent2:alpine-latest
          volumeMounts:
            - name: config
              mountPath: /etc/zabbix/zabbix_agentd.conf
              subPath: zabbix_agentd.conf
          ports:
            - containerPort: 10050
              name: agent
      volumes:
        - name: config
          configMap:
            name: zabbix-agent-config
